### ISSUE TITLE
redirect :back fails in abstract_refresh_geometry_action

### ISSUE THREAD

**Issue by alexdunae** [culturecode/spatial_features#24]
`abstract_refresh_geometry_action` calls `redirect_to :back` which is deprecated in Rails 5 and removed in Rails 6.

Options:
- drop support for old Rails (and allow passing `fallback_location` to this method)
- remove the redirect behaviour and let the host app handle the redirects

**Comment by rywall** [comment]
I will do option 2 :). `redirect_to :back` was actually removed in Rails 5.1 it looks like so I'm going to fix it is `stolo_connect` `master`.
